apiVersion: v1
kind: Service
metadata:
  name: {{ include "hath.fullname" . | quote }}
  labels:
    {{- include "hath.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "hath.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.hath.enableH3 }}
    - name: http3
      port: {{ .Values.service.port }}
      targetPort: http3
      protocol: UDP
    {{- end }}
