{{- if .Values.credentials.renderUserList }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-credential-users" (include "rbac-access.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- include "rbac-access.labels" . | nindent 4 }}
data:
  users.tsv: |-
{{- range .Values.users }}
    {{ .name }}	{{ join "," (.groups | default list) }}
{{- end }}
{{- end }}
