apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  organizationId: af918704-c223-4f10-a245-b4640144f2d9
  secretName: alertmanager-discord
  onlyMappedSecrets: true
  map:
    - bwSecretId: 1a953c0c-b458-4150-830b-b48100db4806
      secretKeyName: webhookUrl
  authToken:
    secretName: bw-auth-token
    secretKey: token
