apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  organizationId: af918704-c223-4f10-a245-b4640144f2d9
  secretName: alertmanager-discord-webhook
  onlyMappedSecrets: true
  map:
    - bwSecretId: 3da86a40-79a8-4bf5-b393-b465001d9995
      secretKeyName: webhook-url
  authToken:
    secretName: bw-auth-token
    secretKey: token
