apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
spec:
  organizationId: "af918704-c223-4f10-a245-b4640144f2d9"
  secretName: grafana-oauth
  onlyMappedSecrets: true
  map:
    - bwSecretId: "8dee8de7-6341-4e72-b7bc-b47800f62f25"
      secretKeyName: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
  authToken:
    secretName: bw-auth-token
    secretKey: token
