nameOverride: ""
fullnameOverride: ""

networkRouter:
  enabled: true
  name: k8s
  namespace: netbird
  annotations: {}
  dnsZoneRef:
    name: k8s.jeiang.vpn
  extraSpec: {}

networkResources:
  enabled: true
  groups: []
  resources:
    - name: blocky-dns
      namespace: dns
      serviceRef:
        name: blocky-dns
      groups:
        - name: dns
    - name: lldap
      namespace: idp
      serviceRef:
        name: idp-lldap
      groups:
        - name: lldap
    - name: longhorn-frontend
      namespace: longhorn-system
      serviceRef:
        name: longhorn-frontend
      groups:
        - name: longhorn
    - name: longhorn-backend
      namespace: longhorn-system
      serviceRef:
        name: longhorn-backend
      groups:
        - name: longhorn
