apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    experimental:
      plugins:
        crowdsec-bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.6.0
    accessLog:
      enabled: true
    additionalArguments:
      - --providers.file.filename=/config/crowdsec-dynamic.yaml
      - --entrypoints.web.http.middlewares=crowdsec-bouncer@file
      - --entrypoints.websecure.http.middlewares=crowdsec-bouncer@file
      - --entrypoints.websecure.transport.respondingtimeouts.readtimeout=15m
    volumes:
      - name: traefik-crowdsec-dynamic
        mountPath: /config
        type: secret
    service:
      annotations:
        load-balancer.hetzner.cloud/name: legion-lb1
        load-balancer.hetzner.cloud/network-zone: us-east
        load-balancer.hetzner.cloud/type: lb11
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/protocol: tcp
        load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
        load-balancer.hetzner.cloud/health-check-protocol: tcp
    ports:
      web:
        proxyProtocol:
          trustedIPs:
            - 10.0.0.0/8
      websecure:
        proxyProtocol:
          trustedIPs:
            - 10.0.0.0/8
