apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      annotations:
        load-balancer.hetzner.cloud/name: legion-lb1
        load-balancer.hetzner.cloud/network-zone: us-east
        load-balancer.hetzner.cloud/type: lb11
        load-balancer.hetzner.cloud/protocol: tcp
        load-balancer.hetzner.cloud/health-check-protocol: tcp
