apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blocky-dns.fullname" . | quote }}
  labels:
    {{- include "blocky-dns.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "blocky-dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blocky-dns.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "blocky-dns.config" . | sha256sum | quote }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: blocky
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BLOCKY_CONFIG_FILE
              value: /app/config.yml
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: dns-tcp
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "blocky-dns.fullname" . | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
