apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bill-splitter.fullname" . }}
  labels:
    {{- include "bill-splitter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bill-splitter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bill-splitter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: bill-splitter
          image: {{ include "bill-splitter.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
