{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bill-splitter.fullname" . }}
  labels:
    {{- include "bill-splitter.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuer.name | quote }}
    {{- end }}
    {{- $mws := list }}
    {{- with .Values.ingress.wafMiddleware }}{{ $mws = append $mws . }}{{- end }}
    {{- if .Values.ingress.redirectToHttps }}{{ $mws = append $mws (printf "%s-%s-redirect-to-https@kubernetescrd" .Release.Namespace (include "bill-splitter.fullname" .)) }}{{- end }}
    {{- if $mws }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," $mws | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" $ }}
                port:
                  name: http
    {{- end }}
{{- end }}
