{{- if and .Values.ingress.enabled .Values.ingress.redirectToHttps }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "bill-splitter.fullname" . }}-redirect-to-https
  namespace: {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
