{{- if .Values.bitwardenSecrets.enabled }}
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: {{ include "attic.secretName" . | quote }}
  labels:
    {{- include "attic.labels" . | nindent 4 }}
spec:
  organizationId: {{ required "bitwardenSecrets.organizationId is required when enabled" .Values.bitwardenSecrets.organizationId | quote }}
  secretName: {{ include "attic.secretName" . | quote }}
  onlyMappedSecrets: true
  map:
    - bwSecretId: {{ required "bitwardenSecrets.secretIds.s3AccessKeyId is required when enabled" .Values.bitwardenSecrets.secretIds.s3AccessKeyId | quote }}
      secretKeyName: {{ .Values.secrets.keys.s3AccessKeyId | quote }}
    - bwSecretId: {{ required "bitwardenSecrets.secretIds.s3SecretAccessKey is required when enabled" .Values.bitwardenSecrets.secretIds.s3SecretAccessKey | quote }}
      secretKeyName: {{ .Values.secrets.keys.s3SecretAccessKey | quote }}
    - bwSecretId: {{ required "bitwardenSecrets.secretIds.tokenRs256SecretBase64 is required when enabled" .Values.bitwardenSecrets.secretIds.tokenRs256SecretBase64 | quote }}
      secretKeyName: {{ .Values.secrets.keys.tokenRs256SecretBase64 | quote }}
  authToken:
    secretName: {{ required "bitwardenSecrets.authToken.secretName is required when enabled" .Values.bitwardenSecrets.authToken.secretName | quote }}
    secretKey: {{ required "bitwardenSecrets.authToken.secretKey is required when enabled" .Values.bitwardenSecrets.authToken.secretKey | quote }}
{{- end }}
