globalAdmins:
  create: true
  clusterRole: cluster-admin
  subjects:
    - kind: Group
      name: kubernetes-admin
      apiGroup: rbac.authorization.k8s.io

breakGlass:
  subjects:
    - kind: User
      name: system:admin
      apiGroup: rbac.authorization.k8s.io
    - kind: Group
      name: system:masters
      apiGroup: rbac.authorization.k8s.io

oidc:
  groups:
    access: kubernetes-access
    admin: kubernetes-admin
    kubeSystemAdmin: kubernetes-kube-system-admin
    kubeSystemReader: kubernetes-kube-system-reader

delegation:
  allowedGroups: []
  allowedClusterRoles:
    - admin
    - view

namespaceLifecycle:
  create: true
  clusterRoleName: namespace-lifecycle
  allowDeletePrefixed: true
  prefixSeparator: "-"
  subjects:
    - kind: Group
      name: kubernetes-access
      apiGroup: rbac.authorization.k8s.io

kubeSystem:
  admin:
    create: true
    clusterRole: admin
    subjects:
      - kind: Group
        name: kubernetes-kube-system-admin
        apiGroup: rbac.authorization.k8s.io
  reader:
    create: true
    clusterRole: view
    subjects:
      - kind: Group
        name: kubernetes-kube-system-reader
        apiGroup: rbac.authorization.k8s.io

kyverno:
  policies:
    create: true
    failureAction: Enforce
  backgroundController:
    createClusterRoleBindings: true
    namespace: kyverno
    subjects:
      - kind: ServiceAccount
        name: kyverno-background-controller
        namespace: kyverno
