{{- if .Values.bitwardenSecrets.netbirdApi.enabled }}
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: {{ .Values.bitwardenSecrets.netbirdApi.secretName | quote }}
  namespace: {{ .Values.bitwardenSecrets.netbirdApi.namespace | quote }}
  labels:
    {{- include "netbird-resources.labels" . | nindent 4 }}
spec:
  organizationId: {{ required "bitwardenSecrets.netbirdApi.organizationId is required when bitwardenSecrets.netbirdApi.enabled=true" .Values.bitwardenSecrets.netbirdApi.organizationId | quote }}
  secretName: {{ .Values.bitwardenSecrets.netbirdApi.secretName | quote }}
  onlyMappedSecrets: true
  map:
    - bwSecretId: {{ required "bitwardenSecrets.netbirdApi.secretId is required when bitwardenSecrets.netbirdApi.enabled=true" .Values.bitwardenSecrets.netbirdApi.secretId | quote }}
      secretKeyName: {{ .Values.bitwardenSecrets.netbirdApi.secretKeyName | quote }}
  authToken:
    secretName: {{ required "bitwardenSecrets.netbirdApi.authToken.secretName is required when bitwardenSecrets.netbirdApi.enabled=true" .Values.bitwardenSecrets.netbirdApi.authToken.secretName | quote }}
    secretKey: {{ required "bitwardenSecrets.netbirdApi.authToken.secretKey is required when bitwardenSecrets.netbirdApi.enabled=true" .Values.bitwardenSecrets.netbirdApi.authToken.secretKey | quote }}
{{- end }}
