global:
  domain: jeiang.dev
  pocketIdHost: auth.jeiang.dev
  lldapHost: ""

secrets:
  existingSecret: idp-secrets
  keys:
    pocketIdEncryptionKey: pocket-id-encryption-key
    pocketIdStaticApiKey: pocket-id-static-api-key
    lldapJwtSecret: lldap-jwt-secret
    lldapKeySeed: lldap-key-seed
    lldapAdminPassword: lldap-admin-password
    pocketIdLdapBindPassword: lldap-admin-password

bitwardenSecrets:
  enabled: true
  organizationId: af918704-c223-4f10-a245-b4640144f2d9
  authToken:
    secretName: bw-auth-token
    secretKey: token
  secretIds:
    lldapJwtSecret: "cc5ad9f3-ce88-4b1c-a9a5-b4650028413d"
    lldapKeySeed: "22be0108-6075-46d7-8b5b-b465002841ca"
    lldapAdminPassword: "384b2038-81d5-45fd-9eca-b46500284255"
    pocketIdEncryptionKey: "d617ec9e-e4b2-4be1-b2e6-b465002842e5"
    pocketIdStaticApiKey: "3c30732f-f3e3-4f68-bbbe-b46500284379"

pocketId:
  replicaCount: 1
  image:
    repository: ghcr.io/pocket-id/pocket-id
    tag: v2.6.2
    pullPolicy: IfNotPresent
  waitForLldap:
    image:
      repository: busybox
      tag: "1.36"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 50m
        memory: 32Mi
  port: 1411
  ldap:
    enabled: true
    bindDn: uid=admin,ou=people,dc=jeiang,dc=dev
    baseDn: dc=jeiang,dc=dev
    usersFilter: "(objectClass=person)"
    groupsFilter: "(objectClass=groupOfUniqueNames)"
    adminGroupName: _pocket_id_admins
    attributes:
      userUniqueIdentifier: entryUUID
      userUsername: uid
      userEmail: mail
      userFirstName: givenName
      userLastName: sn
      groupUniqueIdentifier: entryUUID
      groupName: cn
      groupMember: uniqueMember
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

lldap:
  image:
    repository: lldap/lldap
    tag: stable
    pullPolicy: IfNotPresent
  baseDn: dc=jeiang,dc=dev
  uid: "1000"
  gid: "1000"
  timezone: UTC
  ports:
    ldap: 3890
    http: 17170
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

service:
  pocketId:
    type: ClusterIP
    port: 80
  lldap:
    type: ClusterIP
    ldapPort: 3890
    httpPort: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: idp-tls
  lldap:
    enabled: false

persistence:
  createPersistentVolumes: false
  storageClassName: hcloud-volumes
  reclaimPolicy: Retain
  hostPathBase: /var/lib/idp
  pocketId:
    size: 5Gi
  lldap:
    size: 2Gi

nodeSelector: {}
tolerations: []
affinity: {}
