global:
  domain: jeiang.dev
  pocketIdHost: auth.jeiang.dev

secrets:
  existingSecret: idp-secrets
  keys:
    pocketIdEncryptionKey: pocket-id-encryption-key
    pocketIdStaticApiKey: pocket-id-static-api-key
    pocketIdSmtpPassword: pocket-id-smtp-password

bitwardenSecrets:
  enabled: true
  organizationId: af918704-c223-4f10-a245-b4640144f2d9
  authToken:
    secretName: bw-auth-token
    secretKey: token
  secretIds:
    pocketIdEncryptionKey: "d617ec9e-e4b2-4be1-b2e6-b465002842e5"
    pocketIdStaticApiKey: "3c30732f-f3e3-4f68-bbbe-b46500284379"
    pocketIdSmtpPassword: "53cbe1aa-8d71-4d73-9743-b47500233cc2"

pocketId:
  replicaCount: 1
  image:
    repository: ghcr.io/pocket-id/pocket-id
    tag: v2.9.0
    pullPolicy: IfNotPresent
  port: 1411
  smtp:
    enabled: true
    host: smtp.mail.me.com
    port: 587
    from: noreply@jeiang.dev
    user: jeiang
    tls: starttls
    skipCertVerify: false
  email:
    verificationEnabled: true
    oneTimeAccessAsAdminEnabled: true
    loginNotificationEnabled: true
    apiKeyExpirationEnabled: false
    oneTimeAccessAsUnauthenticatedEnabled: false
  signups:
    allowUserSignups: withToken
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

service:
  pocketId:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: idp-tls

persistence:
  createPersistentVolumes: false
  storageClassName: hcloud-volumes
  reclaimPolicy: Retain
  hostPathBase: /var/lib/idp
  pocketId:
    size: 5Gi

nodeSelector: {}
tolerations: []
affinity: {}
