apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idp.lldapName" . | quote }}
  labels:
    {{- include "idp.labels" . | nindent 4 }}
    app.kubernetes.io/component: lldap
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "idp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: lldap
  template:
    metadata:
      labels:
        {{- include "idp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: lldap
    spec:
      containers:
        - name: lldap
          image: "{{ .Values.lldap.image.repository }}:{{ .Values.lldap.image.tag }}"
          imagePullPolicy: {{ .Values.lldap.image.pullPolicy }}
          env:
            - name: UID
              value: {{ .Values.lldap.uid | quote }}
            - name: GID
              value: {{ .Values.lldap.gid | quote }}
            - name: TZ
              value: {{ .Values.lldap.timezone | quote }}
            - name: LLDAP_LDAP_BASE_DN
              value: {{ .Values.lldap.baseDn | quote }}
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "idp.secretName" . | quote }}
                  key: {{ .Values.secrets.keys.lldapJwtSecret | quote }}
            - name: LLDAP_KEY_SEED
              valueFrom:
                secretKeyRef:
                  name: {{ include "idp.secretName" . | quote }}
                  key: {{ .Values.secrets.keys.lldapKeySeed | quote }}
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "idp.secretName" . | quote }}
                  key: {{ .Values.secrets.keys.lldapAdminPassword | quote }}
          ports:
            - name: ldap
              containerPort: {{ .Values.lldap.ports.ldap }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.lldap.ports.http }}
              protocol: TCP
          resources:
            {{- toYaml .Values.lldap.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-lldap" (include "idp.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "idp.lldapName" . | quote }}
  labels:
    {{- include "idp.labels" . | nindent 4 }}
    app.kubernetes.io/component: lldap
spec:
  type: {{ .Values.service.lldap.type }}
  selector:
    {{- include "idp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lldap
  ports:
    - name: ldap
      port: {{ .Values.service.lldap.ldapPort }}
      targetPort: ldap
      protocol: TCP
    - name: http
      port: {{ .Values.service.lldap.httpPort }}
      targetPort: http
      protocol: TCP
