{{- $fullname := include "idp.fullname" . }}
{{- $labels := include "idp.labels" . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pocket-id" $fullname | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.pocketId.size | quote }}
  storageClassName: {{ $.Values.persistence.storageClassName | quote }}
  {{- if $.Values.persistence.createPersistentVolumes }}
  volumeName: {{ printf "%s-pocket-id" $fullname | trunc 63 | trimSuffix "-" | quote }}
  {{- end }}
