{{- if .Values.persistence.createPersistentVolumes }}
{{- $fullname := include "idp.fullname" . }}
{{- $labels := include "idp.labels" . }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pocket-id" $fullname | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.pocketId.size | quote }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ $.Values.persistence.reclaimPolicy }}
  storageClassName: {{ $.Values.persistence.storageClassName | quote }}
  hostPath:
    path: {{ printf "%s/pocket-id" $.Values.persistence.hostPathBase | quote }}
    type: DirectoryOrCreate
{{- end }}
