apiVersion: v2
name: blocky-dns
description: Internal Blocky DNS resolver
type: application
version: 0.1.3
appVersion: "v0.28.2"
dependencies:
  - name: netbird-resources
    alias: netbird
    version: 0.1.3
    repository: file://../netbird-resources
    condition: netbird.enabled
