apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: traefik-crowdsec-dynamic
  namespace: kube-system
  labels:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/component: traefik-waf
spec:
  organizationId: af918704-c223-4f10-a245-b4640144f2d9
  secretName: traefik-crowdsec-dynamic
  onlyMappedSecrets: true
  map:
    - bwSecretId: 0fc0b4e2-522f-436b-803d-b47a00f7d74d
      secretKeyName: crowdsec-dynamic.yaml
  authToken:
    secretName: bw-auth-token
    secretKey: token
